import type { HtmlReportModel } from "../model";

export function footer(model: HtmlReportModel): string {

    const GITHUB =
  "https://github.com/riturathin/prism-guard";
  const VERSION = "0.1";
  const REPO_NAME = "Prism Guard";

  return `
<footer class="footer">

<hr/>

<div class="footer-content">

<div>

<strong>Generated by Prism Guard v0.1</strong>

</div>

<div>

${model.result.rulesRun} Rules •
${model.result.filesAnalyzed} Files •
${model.result.durationMs} ms

</div>

<div>

<a href="${GITHUB}" target="_blank">${REPO_NAME} v${VERSION}</a>

</div>

</div>

</footer>
`;
}